### ISSUE TITLE
如何与 mirai 一起使用？

### ISSUE THREAD

**Issue by StringKe** [simple-robot/simbot-component-tencent-guild#1]

**Comment by ForteScarlet** [comment]
目前simbot3.x仍处于开发阶段。正式版发布后会在文档中提供组件协同的相关内容。
目前需要等待 `simbot-boot-core 3.x` 以及 3.x版本下的mirai组件编写完毕。

**Comment by ForteScarlet** [comment]
mirai组件已经进入预览阶段，目前理论上二者已经可以配合使用了。
mirai组件仓库地址：https://github.com/simple-robot/simbot-component-mirai

对于组件协同相关文档手册会日后逐步在语雀文档完善：https://www.yuque.com/simpler-robot/simpler-robot-doc
