### ISSUE TITLE
没有支持multipart/form-data消息发送

### ISSUE THREAD

**Issue by ZmjDns** [simple-robot/simbot-component-tencent-guild#45]
官方API发送消息的接口支持，multipart/form-data  **file_image | file | 图片文件。form-data 支持直接通过文件上传的方式发送图片。**
查看了一下本项目的 simbot-component-tencent-guild-api模块，在发送普通消息中没有实现，希望补充一下

**Comment by ForteScarlet** [comment]
可否提供一下官方文档相关内容的连接呢

**Comment by ZmjDns** [comment]
你好，我测试通过这个上传消息的接口https://sandbox.api.sgroup.qq.com/channels/{channelId}/messages，按照文档的数据上传文字和本地图片文件，结果文字发送出去了并且在消息中显示了，但是图片没有在消息中显示并且服务端返回：{"code":40011,"message":"dns resolve"}，找不到官方人解答，只好在这里请教一下，还望大佬指点

**Comment by ForteScarlet** [comment]
你是指你自己在官方SDK或者其他工具（例如postman）上测试产生的上述问题还是使用 `simbot-component-tencent-guild-api` 内api产生的问题呢？
如果是指前者，那有**可能**是提供的参数内容格式不符或者有关审核之类的问题。但是说实话，我不是非常清楚。
由于 [这个原因](https://github.com/orgs/simple-robot/discussions/4)，我们最近一段时间没有太关注QQ频道，因此很多更新或者其他方面的事情我都不太清楚，甚至我都好久没看QQ频道的官方开发者频道了。

不过我觉得你可以试试去它们的频道私聊一下相关的管理员问问，私聊我觉得应该不至于不回复吧
